# .github/workflows/surebets.yml
name: Run Surebet Scraper

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python run_scraper.py

      - name: Commit and push surebets.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/surebets.json
          git commit -m "Update surebets.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
